# Generated by Django 5.2.6 on 2025-11-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='submission_date',
        ),
        migrations.AddField(
            model_name='job',
            name='Address',
            field=models.CharField(default='Not Provided', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='Job_or_company_details',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AddField(
            model_name='job',
            name='Location',
            field=models.CharField(default='Not Provided', max_length=200),
        ),
    ]
